name: Export Notion Document

on:
  schedule:
    - cron: '12 3 * * *' # 毎日午前3時12分に実行
  workflow_dispatch:

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 更新されたバージョン

      - name: Set up Python
        uses: actions/setup-python@v4 # 最新のバージョンを使用

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run export script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          PAGE_ID: ${{ vars.PAGE_ID }}
        run: |
          python export_notion.py

      - name: Check for image link changes
        id: diff-check
        run: |
          git diff HEAD -- exported_document.md > diff.txt
          grep -v '![image]' diff.txt > non_image_diff.txt
          if [ -s non_image_diff.txt ]; then
            echo "non_image_changes=true" >> $GITHUB_ENV
          else
            echo "non_image_changes=false" >> $GITHUB_ENV
          fi
          echo $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add exported_document.md
          git commit -m 'Automated Notion export'
          git push origin master
