name: Export Notion Document

on:
  schedule:
    - cron: '12 3 * * *' # 毎日午前3時12分に実行
  workflow_dispatch:
    branches:
      - notion
  push:
    branches:
      - notion

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 更新されたバージョン

      - name: Set up Python
        uses: actions/setup-python@v4 # 最新のバージョンを使用

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run export script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          PAGE_ID: ${{ vars.PAGE_ID }}
          FILE_NAME: ${{ vars.FILE_NAME }}
        run: |
          python export_notion.py

      - name: Filter diff output
        id: filter-diff
        run: |
          set -e
          git diff HEAD --unified=0 -- exported_document.md > diff.txt
          #echo -------- diff.txt --------
          #cat diff.txt
          grep -E '^[+-][^+-]' diff.txt > diff_filtered.txt
          #echo -------- diff.txt --------
          #cat diff_filtered.txt
          grep -vE '^[+-]!\\[image\\]' diff_filtered.txt > diff_non_image.txt
          echo -------- diff_non_image.txt --------
          cat diff_non_image.txt
          if [ -s diff_non_image.txt ]; then
            echo "non_image_changes=true" >> $GITHUB_ENV
          else
            echo "non_image_changes=false" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: Commit and push changes
        if: env.non_image_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git status
          git add exported_document.md
          git commit -m 'Automated Notion export'
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${GITHUB_REF#refs/heads/}
