name: Test Secrets

on:
  schedule:
    - cron: '12 3 * * *' # 毎日午前3時12分に実行
  workflow_dispatch:
    branches:
      - notion
  push:
    branches:
      - notion

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 更新されたバージョン
        with:
          submodules: true  # サブモジュールもチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v4 # 最新のバージョンを使用

      - name: Run test script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ vars.NOTION_PAGE_ID }}
          NOTION_MD_FILE_NAME: ${{ vars.NOTION_MD_FILE_NAME }}
        run: |
          python export-notion-page/test_secrets.py
